### PR TITLE
fix tests for issue9 issue83 closes #121

### LINKED ISSUE #121: tests fails on 32bit linux
failed issue-9:
```
[1 of 1] Compiling Main             ( Issue9.hs, Issue9.o )
Linking Issue9 ...
PTA:4
AOP:16
(32,64)
64
OK
  Issue #9: [Failed]
ERROR: 
Ran commands: 
cd /home/j/c2hs/tests/bugs/issue-9
rm -f /home/j/c2hs/tests/bugs/issue-9/Issue9.hs
rm -f /home/j/c2hs/tests/bugs/issue-9/Issue9.chs.h
rm -f /home/j/c2hs/tests/bugs/issue-9/Issue9.chi
rm -f /home/j/c2hs/tests/bugs/issue-9/issue9_c.o
rm -f /home/j/c2hs/tests/bugs/issue-9/Issue9
c2hs Issue9.chs
which c2hs
cc -c -o issue9_c.o issue9.c
which cc
ghc -Wall -Werror --make issue9_c.o Issue9.hs
which ghc
/home/j/c2hs/tests/bugs/issue-9/./Issue9
which /home/j/c2hs/tests/bugs/issue-9/./Issue9

Exception: HUnitFailure ""
```

The result is: "PTA:4", "AOP:16", "(32,64)", "64","OK"
Expected is: "PTA:8", "AOP:32", "(32,64)", "64", "OK"
because the size are different.

failed issue-83:
```
[1 of 1] Compiling Main             ( Issue83.hs, Issue83.o )
Linking Issue83 ...
(-1,0)
TEST_VAL
8415
8415
TESTING
  Issue #83: [Failed]
ERROR: 
Ran commands: 
cd /home/j/c2hs/tests/bugs/issue-83
rm -f /home/j/c2hs/tests/bugs/issue-83/Issue83.hs
rm -f /home/j/c2hs/tests/bugs/issue-83/Issue83.chs.h
rm -f /home/j/c2hs/tests/bugs/issue-83/Issue83.chi
rm -f /home/j/c2hs/tests/bugs/issue-83/issue83_c.o
rm -f /home/j/c2hs/tests/bugs/issue-83/Issue83
c2hs Issue83.chs
which c2hs
ghc -Wall -Werror --make Issue83.hs
which ghc
/home/j/c2hs/tests/bugs/issue-83/./Issue83
which /home/j/c2hs/tests/bugs/issue-83/./Issue83

Exception: HUnitFailure ""```
```
The result is: "(-1,0)", "TEST_VAL", "8415", "8415", "TESTING"
Expected is: "(-3,0)", "TEST_VAL", "8415", "8415", "TESTING"
because glibc 'strcmp' return value is "..greater than, equal to, or less than 0...".

i686: strcmp("a", "x") =  -1
 x64: strcmp("a", "x") = -23

System: Linux nixos 3.14.29 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 i686 GNU/Linux

I open a pr ....

### PR DESCRIPTION
**Pull request by j-keck**
see issue #121

### CODE REVIEW

File: tests/test-bugs.hs [hunk 1]
```diff
@@ -280,7 +281,10 @@ issue10 :: Assertion
 issue10 = expect_issue 10 ["SAME", "SAME", "SAME", "SAME"]
 
 issue09 :: Assertion
-issue09 = expect_issue 9 ["PTA:8", "AOP:32", "(32,64)", "64", "OK"]
+issue09 = expect_issue 9 archDependValues
+  where archDependValues
+          | (maxBound::Int) == 2147483647 = ["PTA:4", "AOP:16", "(32,64)", "64", "OK"] -- 32bit
```
Comment (j-keck) [inline tests/test-bugs.hs]: I'm not sure about this architecture check.
If i use 'getSytemID' from 'System.Posix.Unistd' the code is nicer, but doesn't 
run under windows (i think - i have no windows)

**Comment by ian-ross** [comment]
Thanks!  I'll take a look at this today or tomorrow.

**Comment by ian-ross** [comment]
I think that test is fine: it actually tests the thing we care about, which is whether ints are 32 bits or not!  Anyway, merged.  Thanks!
